import streamlit as st
import os
import time
from langchain_community.utilities import SQLDatabase
from langchain_community.agent_toolkits import create_sql_agent
from langchain_google_genai import ChatGoogleGenerativeAI

# ================= CONFIGURATION =================
DB_PATH = "doctors.db"
GEMINI_MODEL = "gemini-2.5-flash"
MAX_RETRIES = 3
RETRY_DELAY = 5  # seconds
# ==================================================

# --- Load API Key ---
try:
    os.environ["GOOGLE_API_KEY"] = st.secrets["GOOGLE_API_KEY"]
except Exception as e:
    st.error("API Key not found. Please configure it in your app's secrets.")
    st.stop()

st.set_page_config(page_title="Dermatologist SQL Agent", page_icon="🩺")
st.title("🩺 Gemini SQL RAG Agent for Doctors DB")
st.write("Ask questions about dermatologists in the database. For example: 'Show all active dermatologists with fee under 1000'.")

# --- Connect to SQLite database ---
try:
    db = SQLDatabase.from_uri(f"sqlite:///{DB_PATH}")
    st.success("✅ Successfully connected to the database.")
except Exception as e:
    st.error(f"❌ Could not connect to database at '{DB_PATH}'. Error: {e}")
    st.stop()

# --- Initialize Gemini LLM with caching ---
@st.cache_resource
def init_llm():
    return ChatGoogleGenerativeAI(model=GEMINI_MODEL, temperature=0)

try:
    llm = init_llm()
except Exception as e:
    st.error(f"❌ Failed to initialize the Language Model. Error: {e}")
    st.stop()

# --- Create SQL Agent ---
try:
    agent = create_sql_agent(llm=llm, db=db, verbose=False, handle_parsing_errors=True)
except Exception as e:
    st.error(f"❌ Failed to create the SQL Agent. Error: {e}")
    st.stop()

# --- Retry wrapper for rate limits ---
def safe_agent_run(agent, query, retries=MAX_RETRIES, delay=RETRY_DELAY):
    for attempt in range(1, retries + 1):
        try:
            return agent.run(query)
        except Exception as e:
            msg = str(e)
            if "RESOURCE_EXHAUSTED" in msg or "Quota exceeded" in msg:
                if attempt < retries:
                    time.sleep(delay)
                else:
                    raise Exception("⏱️ Rate limit exceeded. Please wait a moment and try again.")
            else:
                raise e

# --- Streamlit Form for Query ---
with st.form(key="query_form"):
    user_query = st.text_input("Your Question:")
    submit_button = st.form_submit_button(label="Ask")

if submit_button and user_query:
    try:
        with st.spinner("Generating answer..."):
            response = safe_agent_run(agent, user_query)
        st.subheader("🤖 Answer:")
        st.write(response)

        # Optional: Debug SQL query generated by agent
        with st.expander("Debug SQL Query"):
            st.code(agent._last_query if hasattr(agent, "_last_query") else "No query yet")

    except Exception as e:
        st.error(f"❌ Error: {e}")

st.markdown("---")
st.write("This application uses a Gemini LLM to interact with a SQLite database of dermatologists.")
